# Generated by Django 5.0.14 on 2025-11-12 14:22

import django.db.models.deletion
from django.db import migrations, models


def migrate_roles_to_objects(apps, schema_editor):
    """Create Role objects from existing string values and update User references."""
    User = apps.get_model("accounts", "User")
    Role = apps.get_model("organization", "Role")
    
    # Get all unique role names from users (from the old CharField)
    # We need to use raw SQL to read the old column
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT DISTINCT system_role FROM accounts_user WHERE system_role IS NOT NULL AND system_role != ''")
        role_names = [row[0] for row in cursor.fetchall()]
    
    # Create Role objects for each unique role name
    role_map = {}
    for role_name in role_names:
        if role_name and role_name.strip():
            role, created = Role.objects.get_or_create(name=role_name.strip())
            role_map[role_name.strip()] = role.id
    
    # Update users to reference Role objects using raw SQL
    # Note: system_role_new is the temporary field name
    for role_name, role_id in role_map.items():
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "UPDATE accounts_user SET system_role_new_id = %s WHERE system_role = %s",
                [str(role_id), role_name]
            )


def reverse_migrate_roles_to_strings(apps, schema_editor):
    """Convert Role ForeignKey back to string (for rollback)."""
    User = apps.get_model("accounts", "User")
    Role = apps.get_model("organization", "Role")
    
    # This is complex to reverse, so we'll just set to NULL
    User.objects.update(system_role_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("organization", "0003_role"),
    ]

    operations = [
        # First, add the new ForeignKey field as nullable
        migrations.AddField(
            model_name="user",
            name="system_role_new",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_new",
                to="organization.role",
            ),
        ),
        # Migrate data
        migrations.RunPython(migrate_roles_to_objects, reverse_migrate_roles_to_strings),
        # Remove old field
        migrations.RemoveField(
            model_name="user",
            name="system_role",
        ),
        # Rename new field
        migrations.RenameField(
            model_name="user",
            old_name="system_role_new",
            new_name="system_role",
        ),
    ]
