# Generated by Django 5.0.14 on 2025-11-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_system_role"),
        ("organization", "0005_add_permissions_to_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="system_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="organization.role",
            ),
        ),
    ]
