# Generated by Django 5.0.14 on 2025-12-01 06:03

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_system_role"),
        ("correspondence", "0014_add_performed_by_field"),
        ("dms", "0005_alter_document_document_type_formdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutiveSignature",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        help_text="Encrypted signature image (PNG recommended with transparent background)",
                        upload_to=accounts.models.signature_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the original file for integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "seal_office_name",
                    models.CharField(
                        default="NIGERIAN PORTS AUTHORITY",
                        help_text="Text displayed at top of seal",
                        max_length=100,
                    ),
                ),
                (
                    "seal_office_title",
                    models.CharField(
                        blank=True,
                        help_text="Text displayed at bottom of seal (e.g., 'OFFICE OF THE MANAGING DIRECTOR')",
                        max_length=100,
                    ),
                ),
                (
                    "seal_prefix",
                    models.CharField(
                        default="NPA",
                        help_text="Prefix for seal serial numbers",
                        max_length=20,
                    ),
                ),
                (
                    "require_2fa",
                    models.BooleanField(
                        default=True,
                        help_text="Require 2FA verification before applying seal",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this signature can be used for seals",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this signature was used to generate a seal",
                        null=True,
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this signature has been used",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_signature",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Executive Signature",
                "verbose_name_plural": "Executive Signatures",
            },
        ),
        migrations.CreateModel(
            name="DocumentSeal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        help_text="Unique serial number for verification",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "seal_hash",
                    models.CharField(
                        help_text="Cryptographic hash of the sealed document",
                        max_length=128,
                    ),
                ),
                (
                    "verification_url",
                    models.URLField(
                        blank=True, help_text="URL for QR code verification"
                    ),
                ),
                (
                    "seal_image",
                    models.ImageField(
                        blank=True,
                        help_text="Cached image of the generated seal",
                        null=True,
                        upload_to="seals/generated/",
                    ),
                ),
                ("office_name", models.CharField(max_length=100)),
                ("office_title", models.CharField(max_length=100)),
                ("sealed_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_reason", models.TextField(blank=True)),
                (
                    "correspondence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seals",
                        to="correspondence.correspondence",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seals",
                        to="dms.document",
                    ),
                ),
                (
                    "sealed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applied_seals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signature_used",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seals_created",
                        to="accounts.executivesignature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Seal",
                "verbose_name_plural": "Document Seals",
                "ordering": ["-sealed_at"],
            },
        ),
    ]
