# Generated by Django 5.0.14 on 2025-12-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_last_activity_field"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_last_ac_d21a25_idx",
            old_name="accounts_us_last_ac_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_date_jo_ff39bb_idx",
            old_name="accounts_us_date_jo_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_last_lo_42da58_idx",
            old_name="accounts_us_last_lo_idx",
        ),
    ]
