# Generated by Django 5.0.14 on 2026-01-02 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_rename_accounts_us_last_ac_idx_accounts_us_last_ac_d21a25_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SignatureTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("approval", "Approval"),
                            ("minute", "Minute"),
                            ("forward", "Forward"),
                            ("treatment", "Treatment"),
                        ],
                        help_text="Type of template",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.TextField(
                        help_text="Template format string (e.g., 'APPROVED BY {name}\\n{role}\\n{date}')"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("stamp", "Stamp"),
                            ("formal", "Formal"),
                            ("minimal", "Minimal"),
                        ],
                        default="formal",
                        help_text="Template style",
                        max_length=20,
                    ),
                ),
                (
                    "default_apply",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to apply this template by default for its type",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
            ],
            options={
                "ordering": ["template_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "is_active"],
                        name="accounts_si_templat_0949c4_idx",
                    ),
                    models.Index(
                        fields=["default_apply"], name="accounts_si_default_26c511_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSignaturePreferences",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Template overrides by type: {'approval': 'template_id', 'minute': 'template_id'}",
                    ),
                ),
                (
                    "auto_apply_for_minutes",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically apply signature for minutes",
                    ),
                ),
                (
                    "default_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default template to use",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_users",
                        to="accounts.signaturetemplate",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Signature Preferences",
                "verbose_name_plural": "User Signature Preferences",
            },
        ),
    ]
