# Generated by Django 5.1.15 on 2026-08-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_phase1_login_security_oidc'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0012_acting_request'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id', ''), _negated=True), fields=('employee_id',), name='unique_employee_id_when_set'),
        ),
    ]
