# Generated by Django 5.0.14 on 2025-11-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_office_officemembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON object defining role permissions",
            ),
        ),
    ]
