# Generated by Django 5.0.14 on 2025-12-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_add_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='department',
            new_name='organizatio_name_93bf26_idx',
            old_name='org_dept_name_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='organizatio_code_320010_idx',
            old_name='org_dept_code_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='organizatio_is_acti_635f9b_idx',
            old_name='org_dept_active_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='organizatio_divisio_6949bc_idx',
            old_name='org_dept_div_active_idx',
        ),
        migrations.RenameIndex(
            model_name='directorate',
            new_name='organizatio_name_338475_idx',
            old_name='org_dir_name_idx',
        ),
        migrations.RenameIndex(
            model_name='directorate',
            new_name='organizatio_code_dc1aad_idx',
            old_name='org_dir_code_idx',
        ),
        migrations.RenameIndex(
            model_name='directorate',
            new_name='organizatio_is_acti_c13800_idx',
            old_name='org_dir_active_idx',
        ),
        migrations.RenameIndex(
            model_name='division',
            new_name='organizatio_name_feb403_idx',
            old_name='org_div_name_idx',
        ),
        migrations.RenameIndex(
            model_name='division',
            new_name='organizatio_code_c4cc39_idx',
            old_name='org_div_code_idx',
        ),
        migrations.RenameIndex(
            model_name='division',
            new_name='organizatio_is_acti_98ba5d_idx',
            old_name='org_div_active_idx',
        ),
        migrations.RenameIndex(
            model_name='division',
            new_name='organizatio_directo_de9e42_idx',
            old_name='org_div_dir_active_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='organizatio_name_51df31_idx',
            old_name='org_role_name_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='organizatio_is_acti_a0ce38_idx',
            old_name='org_role_active_idx',
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
