# Generated by Django 5.1.15 on 2026-07-17 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0050_remove_shelf_cabinet_from_location"),
        ("organization", "0009_executivecalendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical location of this office.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offices",
                to="correspondence.location",
            ),
        ),
    ]
