# Generated by Django 5.0.14 on 2026-07-21 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0010_add_location_to_office"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActingAppointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("reason", models.TextField(blank=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("items_transferred", models.PositiveIntegerField(default=0)),
                ("items_reclaimed", models.PositiveIntegerField(default=0)),
                (
                    "transfer_applied",
                    models.BooleanField(
                        default=False,
                        help_text="True after the initial seat-item transfer has been attempted.",
                    ),
                ),
                (
                    "acting_user",
                    models.ForeignKey(
                        help_text="The officer temporarily holding the seat.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_appointments_as_acting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "appointed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acting_appointments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acting_appointments_ended",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        help_text="OfficeMembership(role=acting) created or activated for this appointment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acting_appointments",
                        to="organization.officemembership",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_appointments",
                        to="organization.office",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        help_text="The office holder who is absent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_appointments_as_principal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_at"],
                "indexes": [
                    models.Index(
                        fields=["office", "is_active"],
                        name="organizatio_office__2695bf_idx",
                    ),
                    models.Index(
                        fields=["acting_user", "is_active"],
                        name="organizatio_acting__3953f1_idx",
                    ),
                    models.Index(
                        fields=["principal", "is_active"],
                        name="organizatio_princip_39a3cf_idx",
                    ),
                    models.Index(
                        fields=["ends_at", "is_active"],
                        name="organizatio_ends_at_cfad59_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="actingappointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("office",),
                name="unique_active_acting_appointment_per_office",
            ),
        ),
    ]
