# Generated by Django 5.0.14 on 2026-07-21 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0011_acting_appointment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActingRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why an acting appointment is needed (unreachable, leave, backlog, etc.)."
                    ),
                ),
                (
                    "pending_item_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Open seat items counted when the request was filed.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_requests",
                        to="organization.actingappointment",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_requests",
                        to="organization.office",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        help_text="The absent seat holder this request is about.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_requests_as_principal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acting_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acting_requests_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggested_acting_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional suggested successor.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acting_requests_suggested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="organizatio_status_047619_idx",
                    ),
                    models.Index(
                        fields=["office", "status"],
                        name="organizatio_office__b936f6_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="actingrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("office",),
                name="unique_pending_acting_request_per_office",
            ),
        ),
    ]
