# Generated by Django 5.0.14 on 2025-12-06 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondence', '0015_minute_seal_applied'),
        ('dms', '0006_documentcollection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('reason', models.TextField(help_text='Reason for legal hold')),
                ('case_number', models.CharField(blank=True, max_length=100)),
                ('case_description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='End date of legal hold (null = indefinite)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('correspondences', models.ManyToManyField(blank=True, related_name='legal_holds', to='correspondence.correspondence')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_holds', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='legal_holds', to='dms.document')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('retention_period_days', models.IntegerField(help_text='Number of days to retain before disposition')),
                ('trigger_event', models.CharField(choices=[('creation', 'Document Creation'), ('completion', 'Workflow Completion'), ('last_access', 'Last Access Date'), ('last_modified', 'Last Modified Date')], default='creation', help_text='Event that starts the retention period', max_length=20)),
                ('applies_to', models.CharField(choices=[('document', 'Documents Only'), ('correspondence', 'Correspondence Only'), ('all', 'All Records')], default='all', max_length=20)),
                ('document_types', models.JSONField(blank=True, default=list, help_text='List of document types this policy applies to (empty = all)')),
                ('sensitivity_levels', models.JSONField(blank=True, default=list, help_text='List of sensitivity levels this policy applies to (empty = all)')),
                ('division_ids', models.JSONField(blank=True, default=list, help_text='List of division IDs this policy applies to (empty = all)')),
                ('disposition_action', models.CharField(choices=[('archive', 'Archive'), ('delete', 'Delete'), ('review', 'Review Required'), ('transfer', 'Transfer to Archive')], default='archive', max_length=20)),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether disposition requires manual approval')),
                ('approval_role', models.CharField(blank=True, help_text='Role required to approve disposition (if requires_approval=True)', max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Retention Policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('document', 'Document'), ('correspondence', 'Correspondence')], max_length=20)),
                ('record_id', models.UUIDField(help_text='ID of the document or correspondence')),
                ('action', models.CharField(choices=[('archive', 'Archive'), ('delete', 'Delete'), ('review', 'Review Required'), ('transfer', 'Transfer to Archive')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked by Legal Hold')], default='pending', max_length=20)),
                ('retention_start_date', models.DateTimeField(help_text='Date when retention period started')),
                ('scheduled_date', models.DateTimeField(help_text='Date when disposition should occur')),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('execution_notes', models.TextField(blank=True)),
                ('blocked_by_legal_hold', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dispositions', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_dispositions', to=settings.AUTH_USER_MODEL)),
                ('blocking_legal_holds', models.ManyToManyField(blank=True, related_name='blocked_dispositions', to='records.legalhold')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositions', to='records.retentionpolicy')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='RetentionSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('document', 'Document'), ('correspondence', 'Correspondence')], max_length=20)),
                ('record_id', models.UUIDField()),
                ('retention_start_date', models.DateTimeField()),
                ('retention_end_date', models.DateTimeField(help_text='Date when retention period ends')),
                ('disposition_date', models.DateTimeField(help_text='Date when disposition should occur')),
                ('is_active', models.BooleanField(default=True)),
                ('disposition_created', models.BooleanField(default=False, help_text='Whether a Disposition record has been created')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='records.retentionpolicy')),
            ],
        ),
        migrations.AddIndex(
            model_name='legalhold',
            index=models.Index(fields=['is_active', 'start_date'], name='records_leg_is_acti_f8082a_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionpolicy',
            index=models.Index(fields=['is_active', 'applies_to'], name='records_ret_is_acti_a5be85_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['status', 'scheduled_date'], name='records_dis_status_83e120_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['record_type', 'record_id'], name='records_dis_record__aa9e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionschedule',
            index=models.Index(fields=['record_type', 'record_id'], name='records_ret_record__1a102e_idx'),
        ),
        migrations.AddIndex(
            model_name='retentionschedule',
            index=models.Index(fields=['retention_end_date', 'is_active'], name='records_ret_retenti_da2e86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='retentionschedule',
            unique_together={('record_type', 'record_id', 'policy')},
        ),
    ]
