# Generated by Django 5.0.14 on 2025-11-13 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("in_app_urgent_only", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=True)),
                ("email_urgent_only", models.BooleanField(default=False)),
                ("email_digest", models.BooleanField(default=False)),
                (
                    "email_digest_time",
                    models.TimeField(blank=True, default="09:00", null=True),
                ),
                ("module_dms", models.BooleanField(default=True)),
                ("module_correspondence", models.BooleanField(default=True)),
                ("module_workflow", models.BooleanField(default=True)),
                ("module_system", models.BooleanField(default=True)),
                ("priority_low", models.BooleanField(default=True)),
                ("priority_normal", models.BooleanField(default=True)),
                ("priority_high", models.BooleanField(default=True)),
                ("priority_urgent", models.BooleanField(default=True)),
                ("type_workflow", models.BooleanField(default=True)),
                ("type_document", models.BooleanField(default=True)),
                ("type_correspondence", models.BooleanField(default=True)),
                ("type_system", models.BooleanField(default=True)),
                ("type_alert", models.BooleanField(default=True)),
                ("type_reminder", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, default="22:00", null=True),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, default="07:00", null=True),
                ),
                ("auto_archive_days", models.IntegerField(default=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("workflow", "Workflow"),
                            ("document", "Document"),
                            ("correspondence", "Correspondence"),
                            ("system", "System"),
                            ("alert", "Alert"),
                            ("reminder", "Reminder"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread"),
                            ("read", "Read"),
                            ("archived", "Archived"),
                        ],
                        default="unread",
                        max_length=10,
                    ),
                ),
                ("module", models.CharField(blank=True, max_length=50)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.CharField(blank=True, max_length=255)),
                ("action_url", models.URLField(blank=True)),
                ("action_required", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status", "-created_at"],
                        name="notificatio_recipie_1b3d03_idx",
                    ),
                    models.Index(
                        fields=["recipient", "notification_type", "-created_at"],
                        name="notificatio_recipie_7b2be0_idx",
                    ),
                ],
            },
        ),
    ]
