FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY frontend/package.json ./frontend/
RUN npm install --legacy-peer-deps

COPY frontend/ ./frontend/

WORKDIR /app/frontend
EXPOSE 3002
CMD ["npm", "run", "dev"]