# Generated by Django 5.0.14 on 2025-12-06 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConnector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(choices=[('smtp', 'SMTP'), ('imap', 'IMAP'), ('pop3', 'POP3')], default='smtp', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_incoming', models.BooleanField(default=False, help_text='Whether this connector is for incoming emails')),
                ('is_outgoing', models.BooleanField(default=True, help_text='Whether this connector is for outgoing emails')),
                ('auto_create_correspondence', models.BooleanField(default=False, help_text='Automatically create correspondence from incoming emails')),
                ('default_division_id', models.UUIDField(blank=True, null=True)),
                ('default_department_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ERPConnector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('erp_type', models.CharField(choices=[('oracle', 'Oracle ERP'), ('sap', 'SAP'), ('custom', 'Custom API')], default='oracle', max_length=20)),
                ('base_url', models.URLField(help_text='ERP API base URL')),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication', max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sync_enabled', models.BooleanField(default=False, help_text='Enable automatic synchronization')),
                ('sync_interval_minutes', models.IntegerField(default=60, help_text='Synchronization interval in minutes')),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='Field mappings between ECM and ERP')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('erp', 'ERP'), ('sso', 'SSO')], max_length=20)),
                ('integration_id', models.UUIDField(help_text='ID of the webhook, connector, etc.')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['log_type', 'status', 'created_at'], name='integration_log_typ_d7d8e7_idx'), models.Index(fields=['integration_id', 'created_at'], name='integration_integra_8c5170_idx')],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(help_text='Webhook endpoint URL')),
                ('events', models.JSONField(default=list, help_text="List of event types to subscribe to (e.g., ['document.created', 'correspondence.completed'])")),
                ('secret', models.CharField(help_text='Secret key for webhook signature validation', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retry attempts on failure')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers to include in webhook requests')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text="Event type (e.g., 'document.created')", max_length=100)),
                ('payload', models.JSONField(help_text='Event payload data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['is_active', 'created_at'], name='integration_is_acti_e8b4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['webhook', 'status', 'created_at'], name='integration_webhook_65d78c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', 'status'], name='integration_event_t_83994d_idx'),
        ),
    ]
