# Generated by Django 5.0.14 on 2025-11-10 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_organization', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('direction', models.CharField(choices=[('upward', 'Upward'), ('downward', 'Downward')], default='upward', max_length=20)),
                ('archive_level', models.CharField(blank=True, choices=[('department', 'Department'), ('division', 'Division'), ('directorate', 'Directorate')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence_created', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence_pending', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='organization.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence', to='organization.division')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes')),
                ('file_url', models.URLField(blank=True)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='correspondence.correspondence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceDistribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('division', 'Division'), ('department', 'Department')], max_length=20)),
                ('purpose', models.CharField(choices=[('information', 'For Information'), ('action', 'For Action'), ('comment', 'For Comment')], default='information', max_length=20)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_added', to=settings.AUTH_USER_MODEL)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution', to='correspondence.correspondence')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_entries', to='organization.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_entries', to='organization.division')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceDocumentLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='correspondence.correspondence')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_links', to='dms.document')),
            ],
            options={
                'unique_together': {('correspondence', 'document')},
            },
        ),
        migrations.AddField(
            model_name='correspondence',
            name='linked_documents',
            field=models.ManyToManyField(blank=True, related_name='correspondence_items', through='correspondence.CorrespondenceDocumentLink', to='dms.document'),
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_level', models.CharField(blank=True, max_length=50)),
                ('action_type', models.CharField(choices=[('minute', 'Minute'), ('forward', 'Forward'), ('approve', 'Approve'), ('reject', 'Reject'), ('treat', 'Treat')], default='minute', max_length=20)),
                ('minute_text', models.TextField()),
                ('direction', models.CharField(choices=[('upward', 'Upward'), ('downward', 'Downward')], default='downward', max_length=20)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acted_by_secretary', models.BooleanField(default=False)),
                ('acted_by_assistant', models.BooleanField(default=False)),
                ('assistant_type', models.CharField(blank=True, choices=[('TA', 'Technical Assistant'), ('PA', 'Personal Assistant')], max_length=5)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('signature_payload', models.JSONField(blank=True, null=True)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='correspondence.correspondence')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_in_minutes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_minute', models.BooleanField(default=True)),
                ('can_forward', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('principal', 'assistant')},
            },
        ),
    ]
