# Generated by Django 5.0.14 on 2025-11-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0001_initial"),
        ("organization", "0002_department_is_active_directorate_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondencedistribution",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directorate_distribution_entries",
                to="organization.directorate",
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="correspondencedistribution",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_distribution_entries",
                to="organization.department",
            ),
        ),
        migrations.AlterField(
            model_name="correspondencedistribution",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="division_distribution_entries",
                to="organization.division",
            ),
        ),
        migrations.AlterField(
            model_name="correspondencedistribution",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("division", "Division"),
                    ("department", "Department"),
                    ("directorate", "Directorate"),
                ],
                max_length=20,
            ),
        ),
    ]
