# Generated by Django 5.0.14 on 2025-11-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0002_correspondencedistribution_directorate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
