# Generated by Django 5.0.14 on 2025-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0003_correspondence_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
