# Generated by Django 5.0.14 on 2025-11-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0005_correspondence_offices"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("letter", "Letter"),
                    ("request", "Request"),
                    ("complaint", "Complaint"),
                    ("inquiry", "Inquiry"),
                    ("report", "Report"),
                    ("directive", "Directive"),
                    ("other", "Other"),
                ],
                default="letter",
                max_length=32,
            ),
        ),
    ]
