# Generated by Django 5.0.14 on 2025-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0006_correspondence_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="dispatch_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="letter_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="sender_reference",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
