# Generated by Django 5.0.14 on 2025-11-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0007_correspondence_dispatch_date_and_more"),
        ("dms", "0003_document_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="completion_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="completion_packages",
                to="dms.document",
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="completion_summary_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
