# Generated by Django 5.0.14 on 2025-11-18 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0008_correspondence_completion_package_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="active_parallel_branches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="completed_parallel_branches",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential Processing"),
                    ("parallel", "Parallel Processing"),
                    ("merged", "Branches Merged"),
                    ("waiting_merge", "Waiting for Parallel Branches"),
                ],
                default="sequential",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="edit_history",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="minute",
            name="edit_window_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="is_additional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="minute",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="minute",
            name="is_opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="minute",
            name="is_parallel_branch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="minute",
            name="merge_strategy",
            field=models.CharField(
                choices=[
                    ("all", "Wait for all"),
                    ("independent", "Independent"),
                    ("any", "Any one completes"),
                    ("majority", "Majority completes"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="minute_type",
            field=models.CharField(
                choices=[
                    ("routing", "Routing Minute"),
                    ("instruction", "Additional Instruction"),
                    ("clarification", "Clarification"),
                    ("addendum", "Addendum"),
                ],
                default="routing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="original_minute_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="parallel_group_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="parent_minute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parallel_branches",
                to="correspondence.minute",
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("action", "For Action"),
                    ("information", "For Information"),
                    ("comment", "For Comment"),
                    ("approval", "For Approval"),
                ],
                default="action",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="relates_to_minute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_minutes",
                to="correspondence.minute",
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="requires_response",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="response_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="routing_type",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential"),
                    ("parallel", "Parallel"),
                    ("broadcast", "Broadcast"),
                ],
                default="sequential",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ParallelRoutingGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "merge_strategy",
                    models.CharField(
                        choices=[
                            ("all", "Wait for all"),
                            ("independent", "Independent"),
                            ("any", "Any one completes"),
                            ("majority", "Majority completes"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_branches", models.IntegerField(default=0)),
                ("completed_branches", models.IntegerField(default=0)),
                (
                    "correspondence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parallel_routing_groups",
                        to="correspondence.correspondence",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parallel_routes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
