# Generated by Django 5.0.14 on 2025-11-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0009_add_parallel_routing_and_minute_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="is_recalled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="minute",
            name="recall_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="minute",
            name="recalled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
