# Generated by Django 5.0.14 on 2025-11-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0011_add_to_user_to_minute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="branch_originator",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who originally received this parallel branch (for routing back up hierarchy)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parallel_branches_originated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="consultation_from_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="The minute/branch that requested this consultation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultation_requests",
                to="correspondence.minute",
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="consultation_to_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="The minute/branch that this consultation responds to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultation_responses",
                to="correspondence.minute",
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="is_consultation",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a consultation request from another branch",
            ),
        ),
    ]
