# Generated by Django 5.0.14 on 2025-11-28 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0012_add_branch_originator_and_consultation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceDelegation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Instructions from the executive"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("delegated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assistant",
                    models.ForeignKey(
                        help_text="The assistant who received the delegation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_delegations",
                        to="correspondence.correspondence",
                    ),
                ),
                (
                    "delegation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to the general delegation assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correspondence_delegations",
                        to="correspondence.delegation",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        help_text="The executive who delegated the correspondence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_delegations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-delegated_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="correspondencedelegation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("correspondence", "principal"),
                name="unique_active_delegation_per_correspondence",
            ),
        ),
    ]
