# Generated by Django 5.0.14 on 2025-11-28 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0013_correspondencedelegation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Actual user who performed this action (for delegation audit trail)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minutes_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
