# Generated by Django 5.0.14 on 2025-12-10 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0015_minute_seal_applied"),
        ("dms", "0009_remove_document_dms_document_search_vector_gin_idx"),
        (
            "organization",
            "0008_rename_org_dept_name_idx_organizatio_name_93bf26_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="correspondence",
            index=models.Index(
                fields=["status", "-created_at"], name="corresponde_status_bf4466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correspondence",
            index=models.Index(
                fields=["priority", "-created_at"],
                name="corresponde_priorit_54edf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondence",
            index=models.Index(
                fields=["current_office", "status", "-created_at"],
                name="corresponde_current_d91262_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondence",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="corresponde_created_ad29bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondence",
            index=models.Index(
                fields=["received_date"], name="corresponde_receive_23fb9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correspondence",
            index=models.Index(
                fields=["created_at"], name="corresponde_created_d951d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correspondence",
            index=models.Index(
                fields=["is_deleted", "-created_at"],
                name="corresponde_is_dele_7dc89a_idx",
            ),
        ),
    ]
