# Generated by Django 5.0.14 on 2025-12-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "correspondence",
            "0016_correspondence_corresponde_status_bf4466_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="parent_correspondence",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent correspondence this is responding to (for RE: correspondence)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="response_correspondence",
                to="correspondence.correspondence",
            ),
        ),
    ]
