# Generated by Django 5.0.14 on 2025-12-26 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0019_add_case_enhancements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="case",
            new_name="corresponde_case_nu_5fe491_idx",
            old_name="correspondence_case_number_idx",
        ),
        migrations.RenameIndex(
            model_name="case",
            new_name="corresponde_status_4560e2_idx",
            old_name="correspondence_case_status_opened_idx",
        ),
        migrations.RenameIndex(
            model_name="case",
            new_name="corresponde_case_ty_bdc629_idx",
            old_name="correspondence_case_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="case",
            new_name="corresponde_assigne_277b60_idx",
            old_name="correspondence_case_assigned_status_idx",
        ),
        migrations.RenameIndex(
            model_name="case",
            new_name="corresponde_owning__608e5f_idx",
            old_name="correspondence_case_owning_office_status_idx",
        ),
        migrations.RenameIndex(
            model_name="case",
            new_name="corresponde_is_dele_8ddf55_idx",
            old_name="correspondence_case_is_deleted_opened_idx",
        ),
        migrations.RenameIndex(
            model_name="casecomment",
            new_name="corresponde_case_id_934477_idx",
            old_name="correspond_case_c_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="casecomment",
            new_name="corresponde_parent__f21e8e_idx",
            old_name="correspond_parent_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="casecorrespondencelink",
            new_name="corresponde_case_id_737d5e_idx",
            old_name="correspondence_case_corr_case_primary_idx",
        ),
        migrations.RenameIndex(
            model_name="casedocumentlink",
            new_name="corresponde_case_id_1b9c81_idx",
            old_name="correspondence_case_doc_case_idx",
        ),
        migrations.RenameIndex(
            model_name="caseformlink",
            new_name="corresponde_case_id_7b3236_idx",
            old_name="correspondence_case_form_case_idx",
        ),
        migrations.RenameIndex(
            model_name="casesla",
            new_name="corresponde_case_id_0c1222_idx",
            old_name="correspond_case_t_789ghi_idx",
        ),
        migrations.RenameIndex(
            model_name="casesla",
            new_name="corresponde_breache_05bd7b_idx",
            old_name="correspond_breache_789ghi_idx",
        ),
        migrations.RenameIndex(
            model_name="casetemplate",
            new_name="corresponde_case_ty_96d659_idx",
            old_name="correspond_case_t_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="casetemplate",
            new_name="corresponde_slug_aad88f_idx",
            old_name="correspond_slug_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="caseworkflowrule",
            new_name="corresponde_case_ty_841d1b_idx",
            old_name="correspond_case_t_456def_idx",
        ),
        migrations.RenameIndex(
            model_name="caseworkflowrule",
            new_name="corresponde_trigger_0ca7bb_idx",
            old_name="correspond_trigger_456def_idx",
        ),
        migrations.AddField(
            model_name="case",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Case template used to create this case",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="correspondence.casetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="casecorrespondencelink",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="casedocumentlink",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="caseformlink",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
