# Generated by Django 5.0.14 on 2025-12-29 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0020_add_template_to_case"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="withdraw_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="withdrawn_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who withdrew this correspondence",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correspondence_withdrawn",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="correspondence",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in-progress", "In Progress"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
