# Generated by Django 5.0.14 on 2025-12-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0021_add_withdraw_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondencedistribution",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this distribution entry is active. Set to False when the linked minute is recalled.",
            ),
        ),
        migrations.AddField(
            model_name="correspondencedistribution",
            name="minute",
            field=models.ForeignKey(
                blank=True,
                help_text="The minute that added this distribution entry (if added via minute)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="distribution_entries",
                to="correspondence.minute",
            ),
        ),
    ]
