# Generated by Django 5.0.14 on 2025-12-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0022_add_distribution_minute_link"),
    ]

    operations = [
        migrations.RunSQL(
            # Set database-level default for is_active column
            sql="ALTER TABLE correspondence_correspondencedistribution ALTER COLUMN is_active SET DEFAULT TRUE;",
            reverse_sql="ALTER TABLE correspondence_correspondencedistribution ALTER COLUMN is_active DROP DEFAULT;",
        ),
    ]
