# Generated by Django 5.0.14 on 2025-12-31 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0023_set_is_active_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondencedistribution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User recipient (for parallel routing)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_distribution_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="correspondencedistribution",
            name="purpose",
            field=models.CharField(
                choices=[("information", "For Information"), ("action", "For Action")],
                default="information",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="correspondencedistribution",
            name="recipient_type",
            field=models.CharField(
                choices=[
                    ("division", "Division"),
                    ("department", "Department"),
                    ("directorate", "Directorate"),
                    ("user", "User"),
                ],
                max_length=20,
            ),
        ),
    ]
