# Generated by Django 5.0.14 on 2026-01-02 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0024_add_user_to_distribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Template title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Template description"),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("directorate", "Directorate"),
                            ("division", "Division"),
                            ("department", "Department"),
                            ("user", "User"),
                        ],
                        help_text="Scope level for template access",
                        max_length=32,
                    ),
                ),
                (
                    "scope_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the scope entity (directorate, division, department, or user ID)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("minute", "Minute"),
                            ("treatment", "Treatment"),
                        ],
                        default="document",
                        help_text="Type of template",
                        max_length=32,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minute", "Minute"),
                            ("approve", "Approve"),
                            ("any", "Any"),
                        ],
                        help_text="Action type for minute templates",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "content_html",
                    models.TextField(help_text="HTML content of the template"),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True, help_text="Plain text version of the template"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the default template for its scope",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_correspondence_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_correspondence_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "scope_id", "template_type", "title"],
                "indexes": [
                    models.Index(
                        fields=["scope", "scope_id", "template_type"],
                        name="corresponde_scope_f1696d_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_default"],
                        name="corresponde_is_acti_51b67f_idx",
                    ),
                ],
            },
        ),
    ]
