# Generated by Django 5.0.14 on 2026-01-02 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0025_correspondencetemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceDraft",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "draft_type",
                    models.CharField(
                        choices=[("minute", "Minute"), ("treatment", "Treatment")],
                        help_text="Type of draft (minute or treatment)",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Draft content")),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Optional subject", max_length=255
                    ),
                ),
                (
                    "forward_to",
                    models.CharField(
                        blank=True,
                        help_text="Optional forward to recipient",
                        max_length=255,
                    ),
                ),
                (
                    "on_behalf_of",
                    models.CharField(
                        blank=True,
                        help_text="Optional on behalf of user",
                        max_length=255,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        choices=[("minute", "Minute"), ("approve", "Approve")],
                        help_text="Action type for minute drafts",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "files_metadata",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="File metadata for uploaded files",
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        help_text="The correspondence this draft is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="correspondence.correspondence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this draft",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["correspondence", "user", "draft_type"],
                        name="corresponde_corresp_0b0a9c_idx",
                    ),
                    models.Index(
                        fields=["user", "-updated_at"],
                        name="corresponde_user_id_cf28a9_idx",
                    ),
                ],
                "unique_together": {("correspondence", "user", "draft_type")},
            },
        ),
    ]
