# Generated by Django 5.0.14 on 2026-06-20 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0029_add_office_distribution_recipient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='acknowledged_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('dispatched', 'Dispatched'), ('acknowledged', 'Acknowledged'), ('archived', 'Archived'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DispatchRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_mode', models.CharField(choices=[('email', 'Email'), ('courier', 'Courier'), ('hand_delivery', 'Hand Delivery'), ('postal', 'Postal Service'), ('internal', 'Internal Routing')], max_length=20)),
                ('dispatched_date', models.DateField()),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('courier_name', models.CharField(blank=True, max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_address', models.TextField(blank=True)),
                ('acknowledged_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_records', to=settings.AUTH_USER_MODEL)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='correspondence.correspondence')),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dispatched_date'],
            },
        ),
    ]
