# Generated by Django 5.0.14 on 2026-06-20 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0030_correspondence_acknowledged_date_and_more"),
        (
            "dms",
            "0013_rename_dms_doctempl_is_acti_123abc_idx_dms_documen_is_acti_f6c74a_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("building", models.CharField(max_length=255)),
                ("floor", models.CharField(blank=True, max_length=255)),
                ("room", models.CharField(blank=True, max_length=255)),
                ("shelf", models.CharField(blank=True, max_length=255)),
                ("cabinet", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["building", "floor", "room"],
                "unique_together": {("building", "floor", "room", "shelf", "cabinet")},
            },
        ),
        migrations.CreateModel(
            name="PhysicalDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("tracking_number", models.CharField(max_length=100, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_storage", "In Storage"),
                            ("checked_out", "Checked Out"),
                            ("in_transit", "In Transit"),
                            ("destroyed", "Destroyed"),
                            ("missing", "Missing"),
                        ],
                        default="in_storage",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("expected_return_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "checked_out_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_out_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physical_documents",
                        to="correspondence.correspondence",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physical_documents",
                        to="dms.document",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physical_documents",
                        to="correspondence.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckOutEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("checked_out", "Checked Out"),
                            ("returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="physical_checkout_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "physical_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_events",
                        to="correspondence.physicaldocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="physicaldocument",
            index=models.Index(
                fields=["tracking_number"], name="corresponde_trackin_5e0423_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="physicaldocument",
            index=models.Index(
                fields=["correspondence"], name="corresponde_corresp_6bdb8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="physicaldocument",
            index=models.Index(fields=["status"], name="corresponde_status_cc45fc_idx"),
        ),
        migrations.AddIndex(
            model_name="physicaldocument",
            index=models.Index(
                fields=["location"], name="corresponde_locatio_5525a6_idx"
            ),
        ),
    ]
