# Generated by Django 5.0.14 on 2026-06-20 17:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0031_location_physicaldocument_checkoutevent_and_more"),
        (
            "dms",
            "0013_rename_dms_doctempl_is_acti_123abc_idx_dms_documen_is_acti_f6c74a_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FOIARequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("request_number", models.CharField(max_length=100, unique=True)),
                ("requester_name", models.CharField(max_length=255)),
                ("requester_email", models.EmailField(blank=True, max_length=254)),
                ("requester_phone", models.CharField(blank=True, max_length=50)),
                ("requester_address", models.TextField(blank=True)),
                ("organization", models.CharField(blank=True, max_length=255)),
                (
                    "description_of_documents",
                    models.TextField(
                        help_text="Description of the records/documents being requested"
                    ),
                ),
                ("request_details", models.TextField(blank=True)),
                (
                    "format_preference",
                    models.CharField(
                        choices=[
                            ("electronic", "Electronic"),
                            ("hardcopy", "Hard Copy"),
                            ("inspection", "On-Site Inspection"),
                        ],
                        default="electronic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                            ("in_processing", "In Processing"),
                            ("awaiting_clarification", "Awaiting Clarification"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("partially_granted", "Partially Granted"),
                            ("denied", "Denied"),
                            ("responded", "Responded"),
                            ("closed", "Closed"),
                            ("appealed", "Appealed"),
                        ],
                        default="submitted",
                        max_length=25,
                    ),
                ),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                ("deadline_date", models.DateField(blank=True, null=True)),
                ("acknowledged_date", models.DateField(blank=True, null=True)),
                ("response_date", models.DateField(blank=True, null=True)),
                (
                    "exemption_reason",
                    models.TextField(
                        blank=True, help_text="Legal basis for any exemption/denial"
                    ),
                ),
                (
                    "fees_assessed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fees_waived", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_foia_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_date"],
            },
        ),
        migrations.CreateModel(
            name="FOIANote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True,
                        help_text="Internal notes are not visible to the requester",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "foia_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_entries",
                        to="correspondence.foiarequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FOIARequestDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_response",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a response document (vs a submission attachment)",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="foia_document_additions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foia_documents",
                        to="dms.document",
                    ),
                ),
                (
                    "foia_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="correspondence.foiarequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="foiarequest",
            index=models.Index(
                fields=["status", "-received_date"],
                name="corresponde_status_1cdb90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="foiarequest",
            index=models.Index(
                fields=["request_number"], name="corresponde_request_e6bea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foiarequest",
            index=models.Index(
                fields=["deadline_date"], name="corresponde_deadlin_c769e4_idx"
            ),
        ),
    ]
