# Generated by Django 5.0.14 on 2026-06-24 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0043_backfill_correspondence_current_approver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foiarequest",
            name="received_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
