# Generated by Django 5.1.15 on 2026-07-10 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0046_externalentity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondencedistribution",
            name="read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this distribution entry was marked as read by the recipient",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="correspondencedistribution",
            name="read_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who marked this distribution entry as read",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="read_distributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
