# Generated by Django 5.1.15 on 2026-07-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0047_correspondencedistribution_read_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="branch_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when a parallel branch is force-completed via escalation/non-response handling",
                null=True,
            ),
        ),
    ]
