# Generated by Django 5.1.15 on 2026-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0048_add_branch_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="has_physical_copy",
            field=models.BooleanField(
                default=False,
                help_text="Whether a physical (paper) original exists for this correspondence",
            ),
        ),
    ]
