# Generated by Django 5.1.15 on 2026-07-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0049_add_has_physical_copy_to_correspondence"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("building", "floor", "room")},
        ),
        migrations.RemoveField(
            model_name="location",
            name="cabinet",
        ),
        migrations.RemoveField(
            model_name="location",
            name="shelf",
        ),
    ]
