# Generated by Django 5.0.14 on 2026-07-20 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0052_correspondencedraft_form_data_and_nullable_correspondence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencedraft',
            name='draft_type',
            field=models.CharField(choices=[('minute', 'Minute'), ('treatment', 'Treatment'), ('registration', 'Registration')], help_text='Type of draft (minute or treatment)', max_length=20),
        ),
        migrations.AlterField(
            model_name='physicaldocument',
            name='status',
            field=models.CharField(choices=[('filed', 'Filed'), ('checked_out', 'Checked Out'), ('archived', 'Archived'), ('destroyed', 'Destroyed'), ('missing', 'Missing')], default='filed', max_length=20),
        ),
        migrations.CreateModel(
            name='ReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='correspondence.correspondence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Read Receipt',
                'verbose_name_plural': 'Read Receipts',
                'unique_together': {('user', 'correspondence')},
            },
        ),
    ]
