# Generated by Django 5.0.14 on 2026-07-21 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0053_alter_correspondencedraft_draft_type_and_more"),
        ("organization", "0011_acting_appointment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondence",
            name="acting_appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Active acting appointment that transferred this item's seat ownership.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_items",
                to="organization.actingappointment",
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="acting_original_approver",
            field=models.ForeignKey(
                blank=True,
                help_text="Principal who owned this item before acting reassignment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acting_original_approver_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
