# Generated by Django 5.0.14 on 2026-08-26 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0059_fix_memo_table_no_box_spread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='classification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='classified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondence_classified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='required_approval_level',
            field=models.CharField(choices=[('none', 'None'), ('departmental', 'Departmental'), ('executive', 'Executive')], default='departmental', max_length=16),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='strategic_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minute',
            name='approval_level',
            field=models.CharField(blank=True, choices=[('departmental', 'Departmental'), ('divisional', 'Divisional'), ('executive', 'Executive')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='minute',
            name='approval_role',
            field=models.CharField(blank=True, choices=[('endorsement', 'Endorsement'), ('approval', 'Approval')], max_length=16, null=True),
        ),
    ]
