# Generated by Django 5.0.14 on 2025-11-26 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("correspondence", "0012_add_branch_originator_and_consultation"),
        ("organization", "0005_add_permissions_to_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationRule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("sla_warning", "SLA Warning (Approaching)"),
                            ("sla_breach", "SLA Breach"),
                            ("sla_critical", "SLA Critical"),
                            ("stale", "Stale (No Activity)"),
                            ("priority_urgent", "Urgent Priority Assigned"),
                            ("reassigned", "Item Reassigned"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        JSON conditions for triggering. Examples:\n        - {"priorities": ["urgent", "high"]} - only for these priorities\n        - {"min_days_pending": 3} - only if pending for 3+ days\n        - {"divisions": ["uuid1", "uuid2"]} - only for specific divisions\n        ',
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email_assignee", "Email Assignee"),
                            ("email_manager", "Email Manager"),
                            ("email_division_head", "Email Division Head"),
                            ("email_custom", "Email Custom Recipients"),
                            ("notification", "In-App Notification"),
                            ("auto_escalate", "Auto-Escalate to Manager"),
                            ("daily_digest", "Include in Daily Digest"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        JSON config for the action. Examples:\n        - {"email_template": "sla_warning"} - use specific email template\n        - {"recipients": ["email@example.com"]} - custom recipients\n        - {"escalate_to_role": "division_head"} - role to escalate to\n        ',
                    ),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        blank=True,
                        default="[{priority}] SLA Alert: {subject}",
                        help_text="Subject template. Variables: {priority}, {subject}, {reference}, {days_pending}",
                        max_length=500,
                    ),
                ),
                (
                    "email_body_template",
                    models.TextField(
                        blank=True,
                        help_text="Email body template (HTML). Variables: {priority}, {subject}, {reference}, {days_pending}, {sla_target}, {link}",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority_order",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower numbers execute first"
                    ),
                ),
                (
                    "cooldown_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="Hours before this rule can fire again for the same item",
                    ),
                ),
                (
                    "divisions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all divisions",
                        related_name="escalation_rules",
                        to="organization.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Rule",
                "verbose_name_plural": "Escalation Rules",
                "ordering": ["priority_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SLAConfiguration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this SLA rule", max_length=255
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "correspondence_type",
                    models.CharField(
                        choices=[
                            ("all", "All Types"),
                            ("incoming", "Incoming"),
                            ("outgoing", "Outgoing"),
                            ("internal", "Internal"),
                            ("memo", "Memo"),
                        ],
                        default="all",
                        help_text="Apply to specific correspondence type or all",
                        max_length=20,
                    ),
                ),
                (
                    "target_days",
                    models.PositiveIntegerField(
                        help_text="Number of days to complete within SLA"
                    ),
                ),
                (
                    "warning_threshold_percent",
                    models.PositiveIntegerField(
                        default=75,
                        help_text="Percentage of SLA time elapsed to trigger warning (e.g., 75 = warn at 75%)",
                    ),
                ),
                (
                    "critical_threshold_percent",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Percentage of SLA time elapsed to trigger critical alert (e.g., 90 = critical at 90%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Apply only to this division (leave blank for global)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_configurations",
                        to="organization.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA Configuration",
                "verbose_name_plural": "SLA Configurations",
                "ordering": ["priority", "correspondence_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffPerformanceSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("items_handled", models.PositiveIntegerField(default=0)),
                ("items_completed", models.PositiveIntegerField(default=0)),
                ("items_forwarded", models.PositiveIntegerField(default=0)),
                ("items_returned", models.PositiveIntegerField(default=0)),
                ("avg_response_time_hours", models.FloatField(default=0.0)),
                ("avg_resolution_time_days", models.FloatField(default=0.0)),
                ("sla_compliance_rate", models.FloatField(default=0.0)),
                ("sla_breaches", models.PositiveIntegerField(default=0)),
                (
                    "rework_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Items returned for rework"
                    ),
                ),
                ("first_touch_resolution_rate", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Performance Snapshot",
                "verbose_name_plural": "Staff Performance Snapshots",
                "ordering": ["-week_start", "user"],
            },
        ),
        migrations.CreateModel(
            name="DivisionPerformanceSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("completed_items", models.PositiveIntegerField(default=0)),
                ("pending_items", models.PositiveIntegerField(default=0)),
                (
                    "new_items",
                    models.PositiveIntegerField(
                        default=0, help_text="Items received on this day"
                    ),
                ),
                ("sla_compliant", models.PositiveIntegerField(default=0)),
                ("sla_breached", models.PositiveIntegerField(default=0)),
                (
                    "sla_at_risk",
                    models.PositiveIntegerField(
                        default=0, help_text="Approaching SLA deadline"
                    ),
                ),
                ("sla_compliance_rate", models.FloatField(default=0.0)),
                ("avg_turnaround_days", models.FloatField(default=0.0)),
                ("min_turnaround_days", models.FloatField(default=0.0)),
                ("max_turnaround_days", models.FloatField(default=0.0)),
                (
                    "p50_turnaround_days",
                    models.FloatField(default=0.0, help_text="Median"),
                ),
                (
                    "p90_turnaround_days",
                    models.FloatField(default=0.0, help_text="90th percentile"),
                ),
                ("efficiency_score", models.FloatField(default=0.0)),
                (
                    "throughput",
                    models.FloatField(default=0.0, help_text="Items completed per day"),
                ),
                (
                    "backlog_age_days",
                    models.FloatField(
                        default=0.0, help_text="Average age of pending items"
                    ),
                ),
                ("urgent_count", models.PositiveIntegerField(default=0)),
                ("high_count", models.PositiveIntegerField(default=0)),
                ("medium_count", models.PositiveIntegerField(default=0)),
                ("low_count", models.PositiveIntegerField(default=0)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_snapshots",
                        to="organization.division",
                    ),
                ),
            ],
            options={
                "verbose_name": "Division Performance Snapshot",
                "verbose_name_plural": "Division Performance Snapshots",
                "ordering": ["-snapshot_date", "division"],
                "indexes": [
                    models.Index(
                        fields=["snapshot_date"], name="analytics_d_snapsho_8bac8e_idx"
                    ),
                    models.Index(
                        fields=["division", "snapshot_date"],
                        name="analytics_d_divisio_204640_idx",
                    ),
                ],
                "unique_together": {("division", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("trigger_reason", models.TextField(blank=True)),
                ("action_taken", models.CharField(blank=True, max_length=50)),
                ("action_details", models.JSONField(blank=True, default=dict)),
                ("notified_emails", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="correspondence.correspondence",
                    ),
                ),
                (
                    "notified_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_escalations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalations",
                        to="analytics.escalationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation",
                "verbose_name_plural": "Escalations",
                "ordering": ["-triggered_at"],
                "indexes": [
                    models.Index(
                        fields=["correspondence", "status"],
                        name="analytics_e_corresp_87eaa3_idx",
                    ),
                    models.Index(
                        fields=["triggered_at"], name="analytics_e_trigger_3bdc0b_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="slaconfiguration",
            constraint=models.UniqueConstraint(
                fields=("priority", "correspondence_type", "division"),
                name="unique_sla_config",
            ),
        ),
        migrations.AddIndex(
            model_name="staffperformancesnapshot",
            index=models.Index(
                fields=["week_start"], name="analytics_s_week_st_36e63c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffperformancesnapshot",
            index=models.Index(
                fields=["user", "week_start"], name="analytics_s_user_id_2ab1bf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffperformancesnapshot",
            unique_together={("user", "week_start")},
        ),
    ]
