# Generated by Django 5.0.14 on 2026-06-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_add_sla_and_escalation_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slaconfiguration",
            name="target_days",
            field=models.PositiveIntegerField(
                help_text="Number of hours to complete within SLA"
            ),
        ),
    ]
