"use client";

import { useState } from "react";
import {
  FileText,
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  Calendar,
  Filter,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  Download,
  Upload,
  RefreshCw,
  Clock,
  AlertTriangle,
  CheckCircle,
  Minus,
  MapPin,
  Building,
  Users,
  Activity,
  Globe,
  Zap,
  Shield,
  Database,
  HardDrive,
  Cpu,
  MemoryStick,
  Network,
  Award,
  Star,
  Briefcase,
  DollarSign,
  Percent,
  ArrowUp,
  ArrowDown,
  Circle,
  Square,
  Triangle,
  Monitor,
  Smartphone,
  Laptop,
  Printer,
  Camera,
  Wrench,
  Tool,
  Router,
  Server,
  GitCommit,
  Code,
  GitBranch,
  Play,
  Pause,
  Stop,
  Wifi,
  Bug,
  User,
  Target,
  Gauge,
  Zap as Lightning,
  Layers,
  Link as LinkIcon,
  WifiOff,
  Signal,
  Wifi as WifiIcon,
  Video,
  Headphones,
  Presentation,
  FileVideo,
  Book,
  PenTool,
  Clipboard,
  CheckSquare,
  Square as SquareIcon,
  Navigation,
  Waves,
  Wind,
  Droplets,
  Thermometer,
  Gauge as Speedometer,
  Route,
  Flag,
  Map,
  Settings
} from "lucide-react";
import Link from "next/link";

export default function FinanceReportsPage() {
  const [searchTerm, setSearchTerm] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  const reportStats = [
    {
      name: "Total Reports",
      value: "156",
      change: "+12",
      changeType: "positive",
      icon: FileText,
      description: "Generated this month",
      status: "Growing"
    },
    {
      name: "Scheduled Reports",
      value: "24",
      change: "+3",
      changeType: "positive",
      icon: Calendar,
      description: "Automated reports",
      status: "Active"
    },
    {
      name: "Executive Reports",
      value: "8",
      change: "+1",
      changeType: "positive",
      icon: Award,
      description: "High-level summaries",
      status: "Critical"
    },
    {
      name: "Compliance Reports",
      value: "15",
      change: "0",
      changeType: "neutral",
      icon: Shield,
      description: "Regulatory reports",
      status: "Required"
    }
  ];

  const reports = [
    {
      id: "RPT-001",
      title: "Monthly Financial Performance Report",
      type: "Financial Performance",
      status: "Completed",
      generatedBy: "finance.team@npa.gov.ng",
      generatedDate: "2024-12-10 09:30:00",
      period: "November 2024",
      description: "Comprehensive monthly financial performance analysis including revenue, expenses, and profitability metrics",
      format: "PDF",
      size: "2.4 MB",
      pages: 45,
      recipients: [
        "md@npa.gov.ng",
        "gm.finance@npa.gov.ng",
        "board@npa.gov.ng"
      ],
      dataSources: [
        "General Ledger",
        "Accounts Payable",
        "Accounts Receivable",
        "Budget System"
      ],
      keyMetrics: {
        totalRevenue: "₦45.2B",
        totalExpenses: "₦38.7B",
        netIncome: "₦6.5B",
        budgetVariance: "2.3%",
        cashFlow: "₦8.2B"
      },
      charts: [
        "Revenue Trend Analysis",
        "Expense Breakdown",
        "Profitability Analysis",
        "Budget vs Actual"
      ],
      compliance: {
        standards: ["IFRS", "Nigerian GAAP"],
        auditTrail: "Complete",
        approvalStatus: "Approved"
      },
      schedule: {
        frequency: "Monthly",
        nextGeneration: "2025-01-10 09:00:00",
        autoGenerated: true
      },
      accessLevel: "Executive",
      retention: "7 years",
      tags: ["monthly", "performance", "executive", "financial"]
    },
    {
      id: "RPT-002",
      title: "Quarterly Budget Analysis Report",
      type: "Budget Analysis",
      status: "In Progress",
      generatedBy: "budget.team@npa.gov.ng",
      generatedDate: "2024-12-09 14:15:00",
      period: "Q4 2024",
      description: "Detailed quarterly budget analysis with variance explanations and forecasting",
      format: "Excel",
      size: "1.8 MB",
      pages: 32,
      recipients: [
        "gm.finance@npa.gov.ng",
        "budget.team@npa.gov.ng",
        "division.heads@npa.gov.ng"
      ],
      dataSources: [
        "Budget System",
        "General Ledger",
        "Cost Centers",
        "Department Budgets"
      ],
      keyMetrics: {
        totalRevenue: "₦135.6B",
        totalExpenses: "₦116.1B",
        netIncome: "₦19.5B",
        budgetVariance: "-1.8%",
        cashFlow: "₦24.6B"
      },
      charts: [
        "Budget vs Actual",
        "Variance Analysis",
        "Department Performance",
        "Quarterly Trends"
      ],
      compliance: {
        standards: ["IFRS", "Nigerian GAAP"],
        auditTrail: "In Progress",
        approvalStatus: "Pending"
      },
      schedule: {
        frequency: "Quarterly",
        nextGeneration: "2025-01-15 10:00:00",
        autoGenerated: true
      },
      accessLevel: "Management",
      retention: "5 years",
      tags: ["quarterly", "budget", "analysis", "variance"]
    },
    {
      id: "RPT-003",
      title: "Annual Compliance Report",
      type: "Compliance",
      status: "Completed",
      generatedBy: "compliance.team@npa.gov.ng",
      generatedDate: "2024-12-08 16:45:00",
      period: "2024",
      description: "Annual compliance report covering all regulatory requirements and audit findings",
      format: "PDF",
      size: "4.2 MB",
      pages: 78,
      recipients: [
        "md@npa.gov.ng",
        "gm.finance@npa.gov.ng",
        "audit.committee@npa.gov.ng",
        "regulatory.authority@npa.gov.ng"
      ],
      dataSources: [
        "Audit Reports",
        "Compliance System",
        "Regulatory Filings",
        "Internal Controls"
      ],
      keyMetrics: {
        totalRevenue: "₦542.4B",
        totalExpenses: "₦464.4B",
        netIncome: "₦78.0B",
        budgetVariance: "1.2%",
        cashFlow: "₦98.4B"
      },
      charts: [
        "Compliance Status",
        "Audit Findings",
        "Regulatory Changes",
        "Risk Assessment"
      ],
      compliance: {
        standards: ["IFRS", "Nigerian GAAP", "SOX", "ISO 27001"],
        auditTrail: "Complete",
        approvalStatus: "Approved"
      },
      schedule: {
        frequency: "Annually",
        nextGeneration: "2025-12-31 23:59:00",
        autoGenerated: true
      },
      accessLevel: "Executive",
      retention: "10 years",
      tags: ["annual", "compliance", "regulatory", "audit"]
    },
    {
      id: "RPT-004",
      title: "Weekly Cash Flow Report",
      type: "Cash Flow",
      status: "Completed",
      generatedBy: "treasury.team@npa.gov.ng",
      generatedDate: "2024-12-10 08:00:00",
      period: "Week 49, 2024",
      description: "Weekly cash flow analysis and liquidity position monitoring",
      format: "PDF",
      size: "0.8 MB",
      pages: 12,
      recipients: [
        "treasury.team@npa.gov.ng",
        "gm.finance@npa.gov.ng"
      ],
      dataSources: [
        "Cash Management System",
        "Bank Statements",
        "Accounts Receivable",
        "Accounts Payable"
      ],
      keyMetrics: {
        totalRevenue: "₦10.4B",
        totalExpenses: "₦8.9B",
        netIncome: "₦1.5B",
        budgetVariance: "0.5%",
        cashFlow: "₦2.1B"
      },
      charts: [
        "Cash Flow Statement",
        "Liquidity Position",
        "Bank Balances",
        "Weekly Trends"
      ],
      compliance: {
        standards: ["IFRS", "Nigerian GAAP"],
        auditTrail: "Complete",
        approvalStatus: "Approved"
      },
      schedule: {
        frequency: "Weekly",
        nextGeneration: "2024-12-17 08:00:00",
        autoGenerated: true
      },
      accessLevel: "Management",
      retention: "3 years",
      tags: ["weekly", "cashflow", "liquidity", "treasury"]
    },
    {
      id: "RPT-005",
      title: "Departmental Performance Dashboard",
      type: "Performance",
      status: "Completed",
      generatedBy: "analytics.team@npa.gov.ng",
      generatedDate: "2024-12-09 11:20:00",
      period: "November 2024",
      description: "Interactive dashboard showing departmental performance metrics and KPIs",
      format: "Interactive Dashboard",
      size: "5.6 MB",
      pages: 1,
      recipients: [
        "division.heads@npa.gov.ng",
        "department.managers@npa.gov.ng",
        "gm.finance@npa.gov.ng"
      ],
      dataSources: [
        "HR System",
        "Financial System",
        "Operations System",
        "Performance Metrics"
      ],
      keyMetrics: {
        totalRevenue: "₦45.2B",
        totalExpenses: "₦38.7B",
        netIncome: "₦6.5B",
        budgetVariance: "2.3%",
        cashFlow: "₦8.2B"
      },
      charts: [
        "Department Performance",
        "KPI Trends",
        "Budget Utilization",
        "Efficiency Metrics"
      ],
      compliance: {
        standards: ["IFRS", "Nigerian GAAP"],
        auditTrail: "Complete",
        approvalStatus: "Approved"
      },
      schedule: {
        frequency: "Monthly",
        nextGeneration: "2025-01-09 11:00:00",
        autoGenerated: true
      },
      accessLevel: "Management",
      retention: "5 years",
      tags: ["monthly", "performance", "dashboard", "kpi"]
    }
  ];

  const typeOptions = [
    { value: "all", label: "All Types" },
    { value: "financial_performance", label: "Financial Performance" },
    { value: "budget_analysis", label: "Budget Analysis" },
    { value: "compliance", label: "Compliance" },
    { value: "cash_flow", label: "Cash Flow" },
    { value: "performance", label: "Performance" }
  ];

  const statusOptions = [
    { value: "all", label: "All Status" },
    { value: "completed", label: "Completed" },
    { value: "in_progress", label: "In Progress" },
    { value: "scheduled", label: "Scheduled" },
    { value: "failed", label: "Failed" }
  ];

  const filteredReports = reports.filter(report => {
    const matchesSearch = report.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         report.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         report.generatedBy.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesType = typeFilter === "all" || 
                       report.type.toLowerCase().replace(" ", "_") === typeFilter;
    const matchesStatus = statusFilter === "all" || 
                         report.status.toLowerCase().replace(" ", "_") === statusFilter;
    
    return matchesSearch && matchesType && matchesStatus;
  });

  const statusColorMap = {
    'Completed': 'bg-green-100 text-green-800',
    'In Progress': 'bg-yellow-100 text-yellow-800',
    'Scheduled': 'bg-blue-100 text-blue-800',
    'Failed': 'bg-red-100 text-red-800'
  };

  const typeColorMap = {
    'Financial Performance': 'bg-blue-100 text-blue-800',
    'Budget Analysis': 'bg-green-100 text-green-800',
    'Compliance': 'bg-red-100 text-red-800',
    'Cash Flow': 'bg-purple-100 text-purple-800',
    'Performance': 'bg-orange-100 text-orange-800'
  };

  const accessLevelColorMap = {
    'Executive': 'bg-red-100 text-red-800',
    'Management': 'bg-yellow-100 text-yellow-800',
    'Staff': 'bg-green-100 text-green-800',
    'Public': 'bg-blue-100 text-blue-800'
  };

  const formatColorMap = {
    'PDF': 'bg-red-100 text-red-800',
    'Excel': 'bg-green-100 text-green-800',
    'Interactive Dashboard': 'bg-purple-100 text-purple-800',
    'Word': 'bg-blue-100 text-blue-800'
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Financial Reports</h1>
          <p className="text-gray-600">Generate, manage, and access financial reports and analytics</p>
        </div>
        <div className="flex space-x-3">
          <Link
            href="/finance/planning/reports/create"
            className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Plus className="w-4 h-4 mr-2" />
            Create Report
          </Link>
          <button className="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors">
            <Download className="w-4 h-4 mr-2" />
            Export All
          </button>
        </div>
      </div>

      {/* Report Stats */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {reportStats.map((stat) => (
          <div key={stat.name} className="bg-white rounded-lg shadow-sm border p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">{stat.name}</p>
                <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
                <p className="text-xs text-gray-500">{stat.description}</p>
              </div>
              <stat.icon className="h-8 w-8 text-gray-400" />
            </div>
            <div className="mt-4 flex items-center justify-between">
              <span className={`text-sm font-medium ${
                stat.changeType === 'positive' ? 'text-green-600' : 
                stat.changeType === 'neutral' ? 'text-gray-600' : 'text-red-600'
              }`}>
                {stat.change}
              </span>
              <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                stat.status === 'Growing' ? 'bg-green-100 text-green-800' :
                stat.status === 'Active' ? 'bg-blue-100 text-blue-800' :
                stat.status === 'Critical' ? 'bg-red-100 text-red-800' :
                'bg-yellow-100 text-yellow-800'
              }`}>
                {stat.status}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Search and Filters */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-1">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
              <input
                type="text"
                placeholder="Search reports by title, description, or generator..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
            </div>
          </div>
          <div className="flex gap-4">
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              {typeOptions.map(option => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              {statusOptions.map(option => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
            <button className="inline-flex items-center px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors">
              <Filter className="w-4 h-4 mr-2" />
              More Filters
            </button>
          </div>
        </div>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {filteredReports.map((report) => (
          <div key={report.id} className="bg-white rounded-lg shadow-sm border p-6">
            <div className="flex items-start justify-between mb-4">
              <div className="flex-1">
                <div className="flex items-center space-x-3 mb-2">
                  <FileText className="w-6 h-6 text-blue-600" />
                  <h3 className="text-lg font-semibold text-gray-900">{report.title}</h3>
                  <span className="text-sm text-gray-500">#{report.id}</span>
                </div>
                <p className="text-sm text-gray-600 mb-3">{report.description}</p>
                <div className="flex flex-wrap gap-2 mb-3">
                  <span className={`px-2 py-1 text-xs font-medium rounded-full ${statusColorMap[report.status as keyof typeof statusColorMap]}`}>
                    {report.status}
                  </span>
                  <span className={`px-2 py-1 text-xs font-medium rounded-full ${typeColorMap[report.type as keyof typeof typeColorMap]}`}>
                    {report.type}
                  </span>
                  <span className={`px-2 py-1 text-xs font-medium rounded-full ${formatColorMap[report.format as keyof typeof formatColorMap]}`}>
                    {report.format}
                  </span>
                </div>
              </div>
              <div className="flex space-x-2">
                <button className="p-2 text-blue-600 hover:text-blue-900 hover:bg-blue-50 rounded-lg">
                  <Eye className="w-4 h-4" />
                </button>
                <button className="p-2 text-green-600 hover:text-green-900 hover:bg-green-50 rounded-lg">
                  <Download className="w-4 h-4" />
                </button>
                <button className="p-2 text-purple-600 hover:text-purple-900 hover:bg-purple-50 rounded-lg">
                  <BarChart3 className="w-4 h-4" />
                </button>
              </div>
            </div>

            <div className="border-t border-gray-200 pt-4">
              <div className="grid grid-cols-2 gap-4 mb-4">
                <div>
                  <p className="text-sm font-medium text-gray-900">Generated By</p>
                  <p className="text-sm text-gray-600">{report.generatedBy}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900">Generated Date</p>
                  <p className="text-sm text-gray-600">{report.generatedDate}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900">Period</p>
                  <p className="text-sm text-gray-600">{report.period}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900">Size</p>
                  <p className="text-sm text-gray-600">{report.size}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900">Pages</p>
                  <p className="text-sm text-gray-600">{report.pages}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-900">Access Level</p>
                  <span className={`px-2 py-1 text-xs font-medium rounded-full ${accessLevelColorMap[report.accessLevel as keyof typeof accessLevelColorMap]}`}>
                    {report.accessLevel}
                  </span>
                </div>
              </div>

              <div className="mb-4">
                <p className="text-sm font-medium text-gray-900 mb-2">Key Financial Metrics:</p>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <p className="text-xs text-gray-500">Total Revenue</p>
                    <p className="text-sm font-medium text-green-600">{report.keyMetrics.totalRevenue}</p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500">Total Expenses</p>
                    <p className="text-sm font-medium text-red-600">{report.keyMetrics.totalExpenses}</p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500">Net Income</p>
                    <p className="text-sm font-medium text-gray-900">{report.keyMetrics.netIncome}</p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500">Budget Variance</p>
                    <p className="text-sm font-medium text-gray-900">{report.keyMetrics.budgetVariance}</p>
                  </div>
                </div>
              </div>

              <div className="mb-4">
                <p className="text-sm font-medium text-gray-900 mb-2">Data Sources:</p>
                <div className="flex flex-wrap gap-1">
                  {report.dataSources.map((source, index) => (
                    <span key={index} className="px-2 py-1 text-xs bg-blue-100 text-blue-800 rounded">
                      {source}
                    </span>
                  ))}
                </div>
              </div>

              <div className="mb-4">
                <p className="text-sm font-medium text-gray-900 mb-2">Charts & Visualizations:</p>
                <div className="flex flex-wrap gap-1">
                  {report.charts.map((chart, index) => (
                    <span key={index} className="px-2 py-1 text-xs bg-green-100 text-green-800 rounded">
                      {chart}
                    </span>
                  ))}
                </div>
              </div>

              <div className="mb-4">
                <p className="text-sm font-medium text-gray-900 mb-2">Schedule & Compliance:</p>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <p className="text-xs text-gray-500">Frequency</p>
                    <p className="text-gray-900">{report.schedule.frequency}</p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500">Auto Generated</p>
                    <p className="text-gray-900">{report.schedule.autoGenerated ? "Yes" : "No"}</p>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500">Compliance Status</p>
                    <span className={`px-2 py-1 text-xs rounded-full ${
                      report.compliance.approvalStatus === 'Approved' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                    }`}>
                      {report.compliance.approvalStatus}
                    </span>
                  </div>
                  <div>
                    <p className="text-xs text-gray-500">Retention</p>
                    <p className="text-gray-900">{report.retention}</p>
                  </div>
                </div>
              </div>

              <div className="mb-4">
                <p className="text-sm font-medium text-gray-900 mb-2">Recipients:</p>
                <div className="text-xs text-gray-600">
                  {report.recipients.slice(0, 3).map((recipient, index) => (
                    <div key={index} className="flex items-center space-x-1">
                      <span className="text-blue-600">•</span>
                      <span>{recipient}</span>
                    </div>
                  ))}
                  {report.recipients.length > 3 && (
                    <div className="text-blue-600">+{report.recipients.length - 3} more recipients</div>
                  )}
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div className="flex space-x-2">
                  <button className="inline-flex items-center px-3 py-1 text-sm bg-blue-100 text-blue-700 rounded-lg hover:bg-blue-200">
                    <Eye className="w-3 h-3 mr-1" />
                    View
                  </button>
                  <button className="inline-flex items-center px-3 py-1 text-sm bg-green-100 text-green-700 rounded-lg hover:bg-green-200">
                    <Download className="w-3 h-3 mr-1" />
                    Download
                  </button>
                </div>
                <Link
                  href={`/finance/planning/reports/${report.id}`}
                  className="text-sm text-blue-600 hover:text-blue-700"
                >
                  View Details →
                </Link>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Report Summary */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-lg font-semibold text-gray-900 mb-6">Financial Report Summary</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div className="p-4 border border-gray-200 rounded-lg">
            <div className="flex items-center space-x-3 mb-3">
              <div className="w-8 h-8 bg-green-100 rounded-lg flex items-center justify-center">
                <CheckCircle className="w-4 h-4 text-green-600" />
              </div>
              <div>
                <h3 className="font-medium text-sm">Completed Reports</h3>
                <p className="text-xs text-gray-500">Ready for review</p>
              </div>
            </div>
            <div className="text-sm text-gray-600">
              <p>Count: {reports.filter(r => r.status === 'Completed').length}</p>
              <p>Percentage: {Math.round((reports.filter(r => r.status === 'Completed').length / reports.length) * 100)}%</p>
            </div>
          </div>
          <div className="p-4 border border-gray-200 rounded-lg">
            <div className="flex items-center space-x-3 mb-3">
              <div className="w-8 h-8 bg-blue-100 rounded-lg flex items-center justify-center">
                <Calendar className="w-4 h-4 text-blue-600" />
              </div>
              <div>
                <h3 className="font-medium text-sm">Scheduled Reports</h3>
                <p className="text-xs text-gray-500">Automated generation</p>
              </div>
            </div>
            <div className="text-sm text-gray-600">
              <p>Count: {reports.filter(r => r.schedule.autoGenerated).length}</p>
              <p>Next: {reports.filter(r => r.schedule.autoGenerated)[0]?.schedule.nextGeneration}</p>
            </div>
          </div>
          <div className="p-4 border border-gray-200 rounded-lg">
            <div className="flex items-center space-x-3 mb-3">
              <div className="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center">
                <Award className="w-4 h-4 text-purple-600" />
              </div>
              <div>
                <h3 className="font-medium text-sm">Executive Reports</h3>
                <p className="text-xs text-gray-500">High-level summaries</p>
              </div>
            </div>
            <div className="text-sm text-gray-600">
              <p>Count: {reports.filter(r => r.accessLevel === 'Executive').length}</p>
              <p>Access: Restricted</p>
            </div>
          </div>
          <div className="p-4 border border-gray-200 rounded-lg">
            <div className="flex items-center space-x-3 mb-3">
              <div className="w-8 h-8 bg-yellow-100 rounded-lg flex items-center justify-center">
                <Shield className="w-4 h-4 text-yellow-600" />
              </div>
              <div>
                <h3 className="font-medium text-sm">Compliance Reports</h3>
                <p className="text-xs text-gray-500">Regulatory requirements</p>
              </div>
            </div>
            <div className="text-sm text-gray-600">
              <p>Count: {reports.filter(r => r.type === 'Compliance').length}</p>
              <p>Status: All Compliant</p>
            </div>
          </div>
        </div>
      </div>

      {/* Quick Actions */}
      <div className="bg-white rounded-lg shadow-sm border p-6">
        <h2 className="text-lg font-semibold text-gray-900 mb-4">Report Management Actions</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Link
            href="/finance/planning/reports/create"
            className="p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            <Plus className="h-8 w-8 text-blue-600 mb-3" />
            <h3 className="font-medium text-sm">Create Report</h3>
            <p className="text-xs text-gray-500">New report</p>
          </Link>
          <Link
            href="/finance/planning/reports/schedule"
            className="p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            <Calendar className="h-8 w-8 text-green-600 mb-3" />
            <h3 className="font-medium text-sm">Schedule Reports</h3>
            <p className="text-xs text-gray-500">Automate generation</p>
          </Link>
          <Link
            href="/finance/planning/reports/templates"
            className="p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            <FileText className="h-8 w-8 text-purple-600 mb-3" />
            <h3 className="font-medium text-sm">Report Templates</h3>
            <p className="text-xs text-gray-500">Pre-built templates</p>
          </Link>
          <Link
            href="/finance/planning/reports/analytics"
            className="p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            <BarChart3 className="h-8 w-8 text-yellow-600 mb-3" />
            <h3 className="font-medium text-sm">Report Analytics</h3>
            <p className="text-xs text-gray-500">Usage analytics</p>
          </Link>
        </div>
      </div>
    </div>
  );
}
