# Generated by Django 5.0.14 on 2025-12-06 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms', '0006_documentcollection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='uploading', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('successful_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('process_ocr', models.BooleanField(default=False)),
                ('extract_metadata', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_uploads', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='batch_uploads', to='dms.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptureJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('ocr', 'OCR'), ('scan', 'Scan'), ('batch', 'Batch Processing'), ('metadata', 'Metadata Extraction')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=1)),
                ('processed_items', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_jobs', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capture_jobs', to='dms.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_text', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(default='eng', max_length=10)),
                ('page_count', models.IntegerField(default=0)),
                ('page_results', models.JSONField(blank=True, default=list)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('ocr_engine', models.CharField(default='tesseract', max_length=50)),
                ('capture_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='capture.capturejob')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='dms.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('ready', 'Ready'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='initializing', max_length=20)),
                ('scanner_name', models.CharField(blank=True, max_length=255)),
                ('scan_settings', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
                ('scanned_documents', models.ManyToManyField(blank=True, related_name='scan_sessions', to='dms.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='capturejob',
            index=models.Index(fields=['status', 'created_at'], name='capture_cap_status_7b8c65_idx'),
        ),
        migrations.AddIndex(
            model_name='capturejob',
            index=models.Index(fields=['job_type', 'status'], name='capture_cap_job_typ_87c186_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['document', 'created_at'], name='capture_ocr_documen_c47f11_idx'),
        ),
    ]
