/**
 * API-level types for correspondence endpoints.
 * These mirror the backend serializer output and are validated at runtime
 * by the mapping functions in CorrespondenceContext.
 */

export interface ApiCorrespondence {
  id?: unknown;
  reference_number?: unknown;
  subject?: unknown;
  treatment_response?: unknown;
  document_type?: unknown;
  body_html?: unknown;
  sender_reference?: unknown;
  letter_date?: unknown;
  dispatch_date?: unknown;
  acknowledged_date?: unknown;
  lifecycle_stages?: Record<string, unknown>[];
  dispatch_records?: Record<string, unknown>[];
  source?: unknown;
  received_date?: unknown;
  recipient_name?: unknown;
  remarks?: unknown;
  completed_at?: unknown;
  completion_summary_generated_at?: unknown;
  sender_name?: unknown;
  sender_organization?: unknown;
  sender_email?: unknown;
  sender_phone?: unknown;
  status?: unknown;
  priority?: unknown;
  division?: unknown;
  division_id?: unknown;
  division_name?: unknown;
  department?: unknown;
  department_id?: unknown;
  department_name?: unknown;
  directorate?: unknown;
  directorate_id?: unknown;
  current_approver?: unknown;
  current_approver_id?: unknown;
  created_by?: unknown;
  created_by_id?: unknown;
  direction?: unknown;
  owning_office?: unknown;
  owning_office_id?: unknown;
  owning_office_name?: unknown;
  current_office?: unknown;
  current_office_id?: unknown;
  current_office_name?: unknown;
  attachments?: Record<string, unknown>[];
  distribution?: Record<string, unknown>[];
  parent_correspondence?: unknown;
  archive_level?: unknown;
  linked_document_ids?: unknown[];
  linked_documents?: unknown[];
  completion_package?: unknown;
  case_id?: unknown;
  has_physical_copy?: unknown;
  physical_documents?: Array<Record<string, unknown>>;
  workflow_state?: unknown;
  active_parallel_branches?: unknown;
  completed_parallel_branches?: unknown;
  flow_type?: unknown;
  is_inward?: unknown;
  is_outward?: unknown;
  is_internal?: unknown;
  is_external?: unknown;
  routing_metadata?: unknown;
  created_at?: unknown;
  updated_at?: unknown;
  tags?: unknown;
  is_read?: unknown;
  [key: string]: unknown;
}

export interface ApiMinute {
  id?: unknown;
  correspondence?: unknown;
  correspondence_id?: unknown;
  user?: unknown;
  user_id?: unknown;
  performed_by?: unknown;
  performed_by_id?: unknown;
  performed_by_name?: unknown;
  from_office?: unknown;
  from_office_id?: unknown;
  from_office_name?: unknown;
  to_office?: unknown;
  to_office_id?: unknown;
  to_office_name?: unknown;
  to_user?: unknown;
  to_user_id?: unknown;
  to_user_name?: unknown;
  action_type?: unknown;
  minute_text?: unknown;
  direction?: unknown;
  step_number?: unknown;
  timestamp?: unknown;
  acted_by_secretary?: unknown;
  acted_by_assistant?: unknown;
  assistant_type?: unknown;
  read_at?: unknown;
  mentions?: unknown[];
  grade_level?: unknown;
  seal_data?: unknown;
  signature_payload?: unknown;
  is_edited?: unknown;
  edited_at?: unknown;
  edit_window_expires_at?: unknown;
  is_opened?: unknown;
  opened_at?: unknown;
  original_minute_text?: unknown;
  edit_history?: Record<string, unknown>[];
  can_be_edited?: unknown;
  is_recalled?: unknown;
  recalled_at?: unknown;
  recall_reason?: unknown;
  can_be_recalled?: unknown;
  purpose?: unknown;
  requires_response?: unknown;
  response_deadline?: unknown;
  routing_type?: unknown;
  parallel_group_id?: unknown;
  is_parallel_branch?: unknown;
  parent_minute_id?: unknown;
  parent_minute?: unknown;
  merge_strategy?: unknown;
  minute_type?: unknown;
  is_additional?: unknown;
  relates_to_minute?: unknown;
  relates_to_minute_id?: unknown;
  dispatched_at?: unknown;
  acknowledged_at?: unknown;
  created_at?: unknown;
  updated_at?: unknown;
  [key: string]: unknown;
}
