# Generated by Django 5.0.14 on 2025-11-22 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
        ("organization", "0004_office_officemembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSignatureWorkflow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=0)),
                (
                    "routing_mode",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential - One department at a time"),
                            ("parallel", "Parallel - All departments simultaneously"),
                        ],
                        default="sequential",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_signature_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature_workflows",
                        to="forms.formsubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormSignature",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_label", models.CharField(max_length=255)),
                ("signer_name", models.CharField(blank=True, max_length=255)),
                ("signer_pn", models.CharField(blank=True, max_length=50)),
                ("signer_designation", models.CharField(blank=True, max_length=255)),
                (
                    "signature_file",
                    models.FileField(
                        blank=True, null=True, upload_to="form_signatures/%Y/%m/"
                    ),
                ),
                ("signed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("signed", "Signed"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "assigned_to_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_form_signatures",
                        to="organization.department",
                    ),
                ),
                (
                    "assigned_to_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_form_signatures",
                        to="organization.division",
                    ),
                ),
                (
                    "assigned_to_office",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_form_signatures",
                        to="organization.office",
                    ),
                ),
                (
                    "assigned_to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_form_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_form_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="forms.formsignatureworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="formsignatureworkflow",
            index=models.Index(
                fields=["submission", "status"], name="forms_forms_submiss_12a9a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsignatureworkflow",
            index=models.Index(
                fields=["status", "current_step"], name="forms_forms_status_d87604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsignature",
            index=models.Index(
                fields=["workflow", "status"], name="forms_forms_workflo_1c1b7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formsignature",
            index=models.Index(
                fields=["assigned_to_office", "status"],
                name="forms_forms_assigne_33e416_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formsignature",
            index=models.Index(
                fields=["assigned_to_department", "status"],
                name="forms_forms_assigne_72df69_idx",
            ),
        ),
    ]
