# Generated by Django 5.0.14 on 2026-08-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formsignatureworkflow_formsignature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSerialCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form serial counter',
                'verbose_name_plural': 'Form serial counters',
            },
        ),
    ]
