export const DEFAULT_PAGE_SIZE = 20;

export const NOTIFICATION_POLL_INTERVAL_MS = 30_000;
export const NOTIFICATION_WS_PING_INTERVAL_MS = 30_000;
export const NOTIFICATION_WS_RECONNECT_DELAY_MS = 3_000;
export const NOTIFICATION_WS_MAX_RECONNECT_ATTEMPTS = 5;

