# Generated by Django 5.0.14 on 2025-11-22 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_office_officemembership"),
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps",
                to="organization.directorate",
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_steps",
                to="organization.office",
            ),
        ),
    ]
