# Generated by Django 5.0.14 on 2026-08-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_retire_overlapping_workflows'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='required_approval_level',
            field=models.CharField(blank=True, choices=[('departmental', 'Departmental'), ('divisional', 'Divisional'), ('executive', 'Executive')], max_length=16),
        ),
    ]
