# Generated by Django 5.0.14 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflowstep_required_approval_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplate',
            name='requires_departmental_endorsement',
            field=models.BooleanField(default=True, help_text='If True, EXECUTIVE correspondence must be endorsed at DEPARTMENTAL level before MD approval. If False, direct Officer->MD is allowed.'),
        ),
    ]
