# Generated by Django 5.0.14 on 2025-11-13 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("document_created", "Document Created"),
                            ("document_updated", "Document Updated"),
                            ("document_deleted", "Document Deleted"),
                            ("document_viewed", "Document Viewed"),
                            ("document_downloaded", "Document Downloaded"),
                            ("document_shared", "Document Shared"),
                            ("document_version_uploaded", "Document Version Uploaded"),
                            ("document_comment_added", "Document Comment Added"),
                            ("document_comment_resolved", "Document Comment Resolved"),
                            ("correspondence_created", "Correspondence Created"),
                            ("correspondence_updated", "Correspondence Updated"),
                            ("correspondence_routed", "Correspondence Routed"),
                            ("correspondence_minuted", "Correspondence Minuted"),
                            ("correspondence_approved", "Correspondence Approved"),
                            ("correspondence_rejected", "Correspondence Rejected"),
                            ("correspondence_completed", "Correspondence Completed"),
                            ("user_login", "User Login"),
                            ("user_logout", "User Logout"),
                            ("user_impersonated", "User Impersonated"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("permission_granted", "Permission Granted"),
                            ("permission_revoked", "Permission Revoked"),
                            ("workflow_started", "Workflow Started"),
                            ("workflow_completed", "Workflow Completed"),
                            ("workflow_approved", "Workflow Approved"),
                            ("workflow_rejected", "Workflow Rejected"),
                            ("system_config_changed", "System Configuration Changed"),
                            ("system_backup", "System Backup"),
                            ("system_restore", "System Restore"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=50)),
                ("object_id", models.CharField(blank=True, max_length=255)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("module", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_activ_user_id_9ceb1a_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_activ_action_9f52b2_idx",
                    ),
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_activ_object__6c4d28_idx",
                    ),
                    models.Index(
                        fields=["module", "-timestamp"],
                        name="audit_activ_module_21cb18_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"],
                        name="audit_activ_severit_971d9e_idx",
                    ),
                ],
            },
        ),
    ]
