# Generated by Django 5.0.14 on 2025-11-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentversion",
            name="file_url",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
