# Generated by Django 5.0.14 on 2025-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0002_alter_documentversion_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
