# Generated by Django 5.0.14 on 2025-11-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0003_document_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpermission",
            name="note",
            field=models.TextField(
                blank=True, help_text="Optional message/context included when sharing"
            ),
        ),
    ]
