# Generated by Django 5.0.14 on 2025-11-23 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0011_add_to_user_to_minute"),
        ("dms", "0004_add_note_to_document_permission"),
        ("forms", "0002_formsignatureworkflow_formsignature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("letter", "Letter"),
                    ("memo", "Memo"),
                    ("circular", "Circular"),
                    ("policy", "Policy"),
                    ("report", "Report"),
                    ("form", "Form"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FormDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_data",
                    models.JSONField(
                        default=dict,
                        help_text="The form field data (JSON structure matching template fields)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("awaiting_signatures", "Awaiting Signatures"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        blank=True,
                        help_text="Correspondence this form is linked to (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_documents",
                        to="correspondence.correspondence",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        help_text="The DMS document this form is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_document",
                        to="dms.document",
                    ),
                ),
                (
                    "signature_workflow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Active signature workflow for this form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_documents",
                        to="forms.formsignatureworkflow",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="The form template used for this form",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="form_documents",
                        to="forms.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "status"],
                        name="dms_formdoc_documen_baf7ff_idx",
                    ),
                    models.Index(
                        fields=["template", "status"],
                        name="dms_formdoc_templat_3a27d8_idx",
                    ),
                    models.Index(
                        fields=["correspondence"], name="dms_formdoc_corresp_cd30fc_idx"
                    ),
                ],
            },
        ),
    ]
