# Generated by Django 5.0.14 on 2025-12-06 14:49

import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_documentcollection'),
        ('organization', '0008_rename_org_dept_name_idx_organizatio_name_93bf26_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-updated_at'], name='dms_documen_updated_94f9af_idx'),
        ),
    ]
