# Generated by Django 5.0.14 on 2025-12-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0008_add_search_vector_gin_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="dms_document_search_vector_gin_idx",
        ),
    ]
