# Generated by Django 5.0.14 on 2025-12-10 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0009_remove_document_dms_document_search_vector_gin_idx"),
        (
            "organization",
            "0008_rename_org_dept_name_idx_organizatio_name_93bf26_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["status", "-updated_at"], name="dms_documen_status_4e2df3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "-updated_at"],
                name="dms_documen_documen_d90467_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["author", "-updated_at"], name="dms_documen_author__061f41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["division", "status"], name="dms_documen_divisio_8cedcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_at"], name="dms_documen_created_dcbacd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["document", "-uploaded_at"],
                name="dms_documen_documen_b48bff_idx",
            ),
        ),
    ]
