# Generated by Django 5.0.14 on 2025-12-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0010_document_dms_documen_status_4e2df3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent document this is responding to (for document threads)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="response_documents",
                to="dms.document",
            ),
        ),
    ]
