# Generated by Django 5.0.14 on 2026-06-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0012_add_document_template"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documenttemplate",
            new_name="dms_documen_is_acti_f6c74a_idx",
            old_name="dms_doctempl_is_acti_123abc_idx",
        ),
        migrations.RenameIndex(
            model_name="documenttemplate",
            new_name="dms_documen_created_56ba34_idx",
            old_name="dms_doctempl_created_456def_idx",
        ),
    ]
