# Generated by Django 5.1.14 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dms", "0014_documentrightspolicy_document_drm_policy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrightspolicy",
            name="view_only",
            field=models.BooleanField(
                default=False,
                help_text="When true, users may view but not download or print.",
            ),
        ),
    ]
